version: '3'

services:

  app_db:
    image: mysql:5.7.29
    restart: always
    environment:
      MYSQL_USER: ${API_MYSQL_USER}
      MYSQL_PASSWORD: ${API_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${API_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/init/:/docker-entrypoint-initdb.d/
      - ../src/sql/base/:/srv/sql/01/
      - ../src/sql/sample-data/:/srv/sql/02/

  app_api:
    build:
      context: ..
      dockerfile: docker-dev-env/api/Dockerfile
    depends_on:
      - app_db
    ports:
      - ${API_EXPOSED_PORT}:8080
    environment:
      MYSQL_HOST: app_db
      MYSQL_PORT: 3126
      MYSQL_USER: ${API_MYSQL_USER}
      MYSQL_PASSWORD: ${API_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${API_MYSQL_DATABASE}
      API_HOST: 0.0.0.0
      API_PORT: 8080
    volumes:
      - ../src/api:/srv/api
      - /srv/api/node_modules

  app_client:
    build:
      context: ..
      dockerfile: docker-dev-env/apache/Dockerfile
    depends_on:
      - app_api
    ports:
      - ${GUI_PORT}:80
    environment:
      API_HOST: "localhost"
      API_PORT: ${API_EXPOSED_PORT}
    volumes:
      - ../src/client:/var/www/html
